version: '3.9'
services:
  #
  # mysql service
  #
  mysql_srv:
    image: mysql:8.0
    container_name: mysql_ctr
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_PORT}"
    volumes:
      - ./gym_db.sql:/docker-entrypoint-initdb.d/gym_db.sql
    networks:
      - app-network
  #
  # phpmyadmin service
  #
  phpmyadmin_srv:
    depends_on:
      - mysql_srv
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_ctr
    environment:
      PMA_HOSTS: mysql_srv
      PMA_PORT: ${MYSQL_HOST_PORT}
    ports:
      - ${PMA_HOST_PORT}:${PMA_PORT}
    networks:
      - app-network

  #
  # backend service
  #
  backend_srv:
    build:
      dockerfile: Dockerfile.backend
    depends_on:
      - mysql_srv
    image: nodejs
    container_name: backend_ctr
    ports:
      - ${API_HOST_PORT}:${API_PORT}
    networks:
      - app-network
  #
  # frontend service
  #
  frontend_srv:
    build:
      dockerfile: Dockerfile.frontend
    image: react
    container_name: frontend_ctr
    ports:
      - ${REACT_HOST_PORT}:${REACT_PORT}
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge

volumes:
  mysql_ctr:
  phpadmin_ctr:
  backend_ctr:
  frontend_ctr: