version: '3.9'
services:
  #
  # mysql service
  #
  mysql_srv:
    image: mysql:8.0
    container_name: mysql_ctr
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_PORT}"
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
      - ./logs:/logs
      - ./gym_db.sql:/docker-entrypoint-initdb.d/gym_db.sql
  #
  # phpmyadmin service
  #
  phpmyadmin_srv:
    depends_on:
      - mysql_srv
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_ctr
    restart: always
    environment:
      PMA_HOSTS: mysql_srv
      PMA_PORT: ${MYSQL_HOST_PORT}
    ports:
      - ${PMA_HOST_PORT}:${PMA_PORT}

  #
  # backend service
  #
  backend_srv:
    build:
      dockerfile: Dockerfile.backend
    depends_on:
      - mysql_srv
    image: nodejs
    container_name: backend_ctr
    ports:
      - ${API_HOST_PORT}:${API_PORT}
    volumes:
      - ./backend:/backend
    links:
      - "mysql_srv:database"
  #
  # frontend service
  #
  frontend_srv:
    build:
      dockerfile: Dockerfile.frontend
    image: react
    container_name: frontend_ctr
    ports:
      - ${REACT_HOST_PORT}:${REACT_PORT}
    volumes:
      - ./frontend:/frontend

volumes:
  mysql_srv:
    driver: local