# We are using latest node version
FROM node:latest

# Add a work directory
WORKDIR /backend

# Cache and install dependencies
COPY gym-backend/package*.json .
RUN npm install
RUN npm ci --omit=dev

# Copy app files
COPY gym-backend .

# Expose port
EXPOSE 5000

# Start app
CMD ["npm", "start"]