# We are using latest node version
FROM node:16-alpine3.18

# Add a work directory
WORKDIR /usr/src/app

# Cache and install dependencies
COPY gym-backend/package.json .

RUN npm i

# Copy app files
COPY gym-backend .

# Expose port
EXPOSE 3001

# Start app
CMD ["npm", "start"]